### ISSUE TITLE
mt.write() is not working: hail.utils.java.FatalError: IOException: error=2, No such file or directory

### ISSUE THREAD

**Issue by NLSVTN** [macarthur-lab/hail-elasticsearch-pipelines#185]
I am running the first task **SeqrVCFToMTTask** and all of the steps run successfully until line **63** which is writing out the generated MatrixTable of the final result:

> mt.write(self.output().path, stage_locally=True, overwrite=True)

The output file is created (but its size is 0 bytes). The stack trace that I see is the following:

> Traceback (most recent call last):
>   File "/opt/seqr/.conda/envs/py37/lib/python3.7/site-packages/luigi/worker.py", line 199, in run
>     new_deps = self._run_get_new_deps()
>   File "/opt/seqr/.conda/envs/py37/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
>     task_gen = self.task.run()
>   File "/opt/seqr/hail-elasticsearch-pipelines/luigi_pipeline/seqr_loading.py", line 37, in run
>     self.read_vcf_write_mt()
>   File "/opt/seqr/hail-elasticsearch-pipelines/luigi_pipeline/seqr_loading.py", line 71, in read_vcf_write_mt
>     mt.write(self.output().path, overwrite=True)
>   File "</opt/seqr/.conda/envs/py37/lib/python3.7/site-packages/decorator.py:decorator-gen-1036>", line 2, in write
>   File "/opt/seqr/hail-elasticsearch-pipelines/hail_builds/v02/hail-0.2-3a68be23cb82d7c7fb5bf72668edcd1edf12822e.zip/hail/typecheck/check.py", line 585, in wrapper
>     return __original_func(*args_, **kwargs_)
>   File "/opt/seqr/hail-elasticsearch-pipelines/hail_builds/v02/hail-0.2-3a68be23cb82d7c7fb5bf72668edcd1edf12822e.zip/hail/matrixtable.py", line 2508, in write
>     Env.backend().execute(MatrixWrite(self._mir, writer))
>   File "/opt/seqr/hail-elasticsearch-pipelines/hail_builds/v02/hail-0.2-3a68be23cb82d7c7fb5bf72668edcd1edf12822e.zip/hail/backend/backend.py", line 109, in execute
>     result = json.loads(Env.hc()._jhc.backend().executeJSON(self._to_java_ir(ir)))
>   File "/opt/seqr/spark/spark-2.4.4-bin-hadoop2.7/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
>     answer, self.gateway_client, self.target_id, self.name)
>   File "/opt/seqr/hail-elasticsearch-pipelines/hail_builds/v02/hail-0.2-3a68be23cb82d7c7fb5bf72668edcd1edf12822e.zip/hail/utils/java.py", line 225, in deco
>     'Error summary: %s' % (deepest, full, hail.__version__, deepest)) from None
> hail.utils.java.FatalError: IOException: error=2, No such file or directory
> 
> Java stack trace:
> org.apache.spark.SparkException: Job aborted due to stage failure: Task 3 in stage 7.0 failed 1 times, most recent failure: Lost task 3.0 in stage 7.0 (TID 2666, localhost, executor driver): java.io.IOException: Cannot run program "/vep": error=2, No such file or directory
> 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
> 	at is.hail.utils.richUtils.RichIterator$.pipe$extension(RichIterator.scala:47)

I found almost identical thread on Hail 0.2 forum:

https://discuss.hail.is/t/cant-write-vep-annotated-hail-table/855/3

And the issue is that **VEP** fails because **Hail** can't find path to **/vep** that is specified in **vep85-loftee-local.json** config file. Ok, but is it possible to install **VEP** on **hadoop** (in your case Google Cloud)? Or somehow change dynamically the path that Hail accesses in the **luigi** pipeline? Locally VEP is intalled, and I copying all what could have been copied to **hadoop** for **VEP** (while copying to **hadoop** it gives an error: **filepath is not a valid DFS filename** since there are such names of the files, e.g.: **Bio::DB::HTS.3pm**).

**Comment by NLSVTN** [comment]
I tried specifying local paths in the vep config file and apparently it reads from the local file system, however, I am still getting an error, just that VEP was invoked and then failed fro an unknown reason:

Error summary: HailException: VEP command 'variant_effect_predictor.pl --format vcf --json --everything --allele_number --no_stats --cache --offline --minimal --assembly GRCh37 --plugin LoF,human_ancestor_fa:loftee_data/human_ancestor.fa.gz,filter_position:0.05,min_intron_size:15,conservation_file:loftee_data/phylocsf.sql,gerp_file:loftee_data/GERP_scores.final.sorted.txt.gz,run_splice_predictions:0 -o STDOUT' failed with non-zero exit status 2
  VEP Error output:

**Comment by NLSVTN** [comment]
After modifying VEP command and apparently running it successfully, I faced another error:

**Comment by NLSVTN** [comment]
I am still having other issues downstream of pipeline execution but they seem to be different from the current issue. The solution to the current one was to specify local paths (and not **hadoop** ones) to the config file that Hail's **vep()** function gets.
