### ISSUE TITLE
hail export VCF errors

### ISSUE THREAD

**Issue by samarthaFFM** [macarthur-lab/hail-elasticsearch-pipelines#207]
Hi guys,

In the export vcf command in the hail_scripts, v01 script 'load_dataset_to_es.py' given below - 

    if args.export_vcf:
        logger.info("Writing out to VCF...")
        vds.export_vcf(args.step0_output_vcf, overwrite=True)

the overwrite parameter throws an error as the argument does not exist, here is my code - 

Stage 4:====================================================>(2956 + 1) / 2957]2020-07-26 12:36:59,314 INFO     Writing out to VCF...
Traceback (most recent call last):
  File "/home/ttysam01/Seqr_install/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 900, in <module>
    run_pipeline()
  File "/home/ttysam01/Seqr_install/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 867, in run_pipeline
    hc, vds = step0_init_and_run_vep(hc, vds, args)
  File "/home/ttysam01/Seqr_install/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 162, in wrapper
    result = f(*args, **kwargs)
  File "/home/ttysam01/Seqr_install/seqr/hail_elasticsearch_pipelines/hail_scripts/v01/load_dataset_to_es.py", line 439, in step0_init_and_run_vep
    vds.export_vcf(args.step0_output_vcf, overwrite=True)
TypeError: export_vcf() got an unexpected keyword argument 'overwrite'

Is it okay if I just remove the parameter?

**Comment by hanars** [comment]
yeah that should be fine, or you could not use the --export-vcf flag

**Comment by samarthaFFM** [comment]
Hi @hanars, thanks for the answer. I wanted to do some filtering and analysis on the annotated Vcf file which is why I wanted to export the vcf. Is there a way to do this with out the --export-vcf flag and using hail to read the data?

**Comment by hanars** [comment]
nope, if you want the annotated vcf you need to use the --export-vcf flag, so I would recommend removing the parameter

**Comment by samarthaFFM** [comment]
great, will do. Thanks again
